name = "RasterDataSources"
uuid = "3cb90ccd-e1b6-4867-9617-4276c8b2ca36"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>", "Timothée Poisot <timothee.poisot@umontreal.ca>"]
version = "0.3.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
HTTP = "0.8, 0.9"
URIs = "1"
ZipFile = "0.9"
julia = "1.5"
