name = "SimpleSDMDataSources"
uuid = "223ac6fb-8ff2-47bc-8662-ddfd67b53883"
authors = ["Timothée Poisot <timothee.poisot@umontreal.ca>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
HTTP = "0.8"
