# Generator for the Copernicus DEM tile coverage map in `src/copernicus_dem/coverage.jl`.
#
# Reads the authoritative `tileList.txt` published alongside each resolution's
# AWS Open Data bucket and writes a human-readable `BitArray` of 1s (a 1°×1°
# tile exists) and 0s (no tile, i.e. open ocean). The matrix is laid out like a
# world map: one row per degree of latitude (north at the top, 89° down to
# -90°), one column per degree of longitude (-180° to 179°).
#
# GLO-30 (30m) is a strict subset of GLO-90 (90m): the only difference is a
# handful of tiles in the Caucasus that exist at 90m but not 30m. So we write
# the 30m coverage as the map and list the 90m-only tiles separately.
#
# Re-run this when Copernicus publishes a new DEM version:
#   curl -s https://copernicus-dem-30m.s3.amazonaws.com/tileList.txt -o /tmp/cop30.txt
#   curl -s https://copernicus-dem-90m.s3.amazonaws.com/tileList.txt -o /tmp/cop90.txt
#   julia dev/gen_copernicus_coverage.jl

# Grid: row 1 = northernmost tile (SW corner lat 89, covering 89..90),
#       row 180 = southernmost (SW corner lat -90, covering -90..-89);
#       col 1 = westernmost (SW corner lon -180), col 360 = easternmost (lon 179).
const NLAT = 180
const NLON = 360

# SW-corner (lat, lon) integer degrees -> matrix (row, col)
_row(lat) = 90 - lat
_col(lon) = lon + 181

function parse_tile(line)
    # Copernicus_DSM_COG_10_N42_00_E011_00_DEM
    m = match(r"_(N|S)(\d{2})_00_(E|W)(\d{3})_00_DEM$", line)
    m === nothing && error("Unrecognised tile name: $line")
    ns, latd, ew, lond = m.captures
    lat = (ns == "S" ? -1 : 1) * parse(Int, latd)
    lon = (ew == "W" ? -1 : 1) * parse(Int, lond)
    return lat, lon
end

function coverage_from_list(path)
    M = falses(NLAT, NLON)
    for line in eachline(path)
        isempty(line) && continue
        lat, lon = parse_tile(line)
        M[_row(lat), _col(lon)] = true
    end
    return M
end

M30 = coverage_from_list("/tmp/cop30.txt")
M90 = coverage_from_list("/tmp/cop90.txt")
extra = findall(M90 .& .!M30)  # tiles only in the 90m dataset

@info "tile counts" n30 = count(M30) n90 = count(M90) extra = length(extra)

open(joinpath(@__DIR__, "..", "src", "copernicus_dem", "coverage.jl"), "w") do io
    println(io, "# Generated by dev/gen_copernicus_coverage.jl from the Copernicus DEM")
    println(io, "# `tileList.txt` files. Each entry is one 1°×1° tile: 1 = the tile exists,")
    println(io, "# 0 = open ocean (no tile). Laid out as a world map — row 1 is latitude")
    println(io, "# 89°..90° (north) down to row 180 at -90°..-89°, column 1 is longitude")
    println(io, "# -180°..-179° (west) across to column 360 at 179°..180°. This is the")
    println(io, "# GLO-30 (30m) coverage; GLO-90 (90m) adds the tiles in")
    println(io, "# `COPERNICUS_DEM_90M_EXTRA` below.")
    println(io, "const HAS_COPERNICUS_DEM_TILE_30M = BitArray([")
    for r in 1:NLAT
        print(io, "    ")
        println(io, join((M30[r, c] ? '1' : '0' for c in 1:NLON), ' '))
    end
    println(io, "])")
    println(io)
    println(io, "# Tiles present only in the GLO-90 (90m) dataset (a cluster in the Caucasus).")
    println(io, "# Listed as `CartesianIndex(row, col)` into the grid above.")
    println(io, "const COPERNICUS_DEM_90M_EXTRA = [")
    for I in extra
        lat = 90 - I[1]   # inverse of _row
        lon = I[2] - 181  # inverse of _col
        latlab = lat < 0 ? "S$(lpad(-lat,2,'0'))" : "N$(lpad(lat,2,'0'))"
        lonlab = lon < 0 ? "W$(lpad(-lon,3,'0'))" : "E$(lpad(lon,3,'0'))"
        println(io, "    CartesianIndex($(I[1]), $(I[2])),  # $latlab $lonlab")
    end
    println(io, "]")
end

println("Wrote src/copernicus_dem/coverage.jl")
