
"""
    CopernicusDEM <: RasterDataSource

The Copernicus Digital Elevation Model (GLO-30 and GLO-90), a global digital
surface model derived from the WorldDEM, hosted as Cloud-Optimized GeoTIFFs on
the AWS Open Data registry (no authentication required).

The dataset is split into 1°×1° tiles. Oceanic tiles that contain no land are
absent from the dataset and are returned as `missing`.

See: [Copernicus DEM on AWS](https://registry.opendata.aws/copernicus-dem/)

# Usage with `getraster`

    getraster(T::Type{CopernicusDEM}; extent, res) => Matrix{Union{String,Missing}}
    getraster(T::Type{CopernicusDEM}; bounds, res) => Matrix{Union{String,Missing}}
    getraster(T::Type{CopernicusDEM}; tile_index, res) => String

## Keywords

- `res`: `String` chosen from `("30m", "90m")`, `"30m"` by default.
- `extent`: an `Extents.Extent`, the canonical spatial selector. All 1°×1° tiles
    intersecting the extent are downloaded, returning a `Matrix` of file paths
    (with `missing` for non-existent oceanic tiles).
- `bounds`: a legacy alias for `extent`, also accepting a `Tuple` of
    `(longitudes, latitudes)` bounds.
- `tile_index`: a `CartesianIndex` (or `CartesianIndices`) addressing tiles by the
    integer degrees of their south-west corner. Mostly used internally.

## Example

```julia
using RasterDataSources, Extents
# 30m tiles intersecting an extent over Italy
getraster(CopernicusDEM; extent=Extent(X=(10, 12), Y=(41, 43)), res="30m")
```
"""
struct CopernicusDEM <: RasterDataSource end

# Copernicus DEM tile coverage (generated by `dev/gen_copernicus_coverage.jl`). 
include_dependency(joinpath(@__DIR__, "coverage.txt"))
const _COPERNICUS_DEM_COVERAGE =
    readdlm(joinpath(@__DIR__, "coverage.txt"), Int)

const HAS_COPERNICUS_DEM_TILE_30M = BitMatrix(_COPERNICUS_DEM_COVERAGE .& 1 .!= 0)
const HAS_COPERNICUS_DEM_TILE_90M = BitMatrix(_COPERNICUS_DEM_COVERAGE .& 2 .!= 0)

resolutions(::Type{CopernicusDEM}) = ("30m", "90m")
defres(::Type{CopernicusDEM}) = "30m"

# Per-resolution AWS Open Data bucket and the number embedded in the tile name
# (`10` for 30m, `30` for 90m). `res` is always "30m" or "90m" here, validated
# by `_check_res` before any of these are called.
_res_bucket(res) = res == "30m" ? "copernicus-dem-30m" : "copernicus-dem-90m"
_res_code(res) = res == "30m" ? "10" : "30"

_coverage(res) = res == "30m" ? HAS_COPERNICUS_DEM_TILE_30M : HAS_COPERNICUS_DEM_TILE_90M

getraster_keywords(::Type{CopernicusDEM}) = (:bounds, :extent, :tile_index, :res)

# Tile addressing. A tile is identified by the integer degrees of its
# south-west corner, stored as a `CartesianIndex` into the coverage grid.
_cop_row(lat::Integer) = 90 - lat
_cop_col(lon::Integer) = lon + 181
_cop_lat(row::Integer) = 90 - row
_cop_lon(col::Integer) = col - 181

function _raster_tile_stem(::Type{CopernicusDEM}, tile_index::CartesianIndex{2}, res)
    row, col = tile_index.I
    lat, lon = _cop_lat(row), _cop_lon(col)
    ns = lat < 0 ? 'S' : 'N'
    ew = lon < 0 ? 'W' : 'E'
    code = _res_code(res)
    "Copernicus_DSM_COG_$(code)_$(ns)$(lpad(abs(lat), 2, '0'))_00_$(ew)$(lpad(abs(lon), 3, '0'))_00_DEM"
end

_rastername(T::Type{CopernicusDEM}, tile_index::CartesianIndex{2}; res=defres(T)) =
    _raster_tile_stem(T, tile_index, res) * ".tif"
_rasterpath(T::Type{CopernicusDEM}, tile_index::CartesianIndex{2}; res=defres(T)) =
    joinpath(rasterpath(), "CopernicusDEM", res, _rastername(T, tile_index; res))

function _rasterurl(T::Type{CopernicusDEM}, tile_index::CartesianIndex{2}; res=defres(T))
    stem = _raster_tile_stem(T, tile_index, res)
    URI(scheme="https", host="$(_res_bucket(res)).s3.amazonaws.com",
        path="/$stem/$stem.tif")
end

function _getraster(T::Type{CopernicusDEM}, tile_index::CartesianIndex{2}; res=defres(T))
    raster_path = _rasterpath(T, tile_index; res)
    if !isfile(raster_path)
        @info "Note: not all oceanic tiles exist in the Copernicus DEM dataset."
        _maybe_download(_rasterurl(T, tile_index; res), raster_path)
    end
    return raster_path
end

# Map a coordinate to the south-west corner of the 1°×1° tile that contains it.
function bounds_to_tile_indices(::Type{CopernicusDEM}, bounds::NTuple{4,Real})
    bounds_to_tile_indices(CopernicusDEM, ((bounds[1], bounds[3]), (bounds[2], bounds[4])))
end
function bounds_to_tile_indices(::Type{CopernicusDEM}, ext::Extents.Extent)
    bounds_to_tile_indices(CopernicusDEM, (ext.X, ext.Y))
end
function bounds_to_tile_indices(::Type{CopernicusDEM}, (xs, ys)::NTuple{2,NTuple{2,Real}})
    _check_order(xs)
    _check_order(ys)
    cols = _cop_col(floor(Int, xs[1])):_cop_col(floor(Int, xs[2]))
    # Rows increase southward, so the upper latitude maps to the smaller row.
    rows = _cop_row(floor(Int, ys[2])):_cop_row(floor(Int, ys[1]))
    return CartesianIndices((rows, cols))
end

for op in (:getraster, :rastername, :rasterpath, :rasterurl)
    _op = Symbol('_', op) # Name of internal function
    @eval begin
        # Broadcasting function dispatch over a range of tiles
        function $_op(T::Type{CopernicusDEM}, tile_index::CartesianIndices; res=defres(T))
            broadcast(tile_index) do I
                _coverage(res)[I] ? $_op(T, I; res) : missing
            end
        end
        # Bounds to tile indices dispatch
        $_op(T::Type{CopernicusDEM}, bounds::Tuple; res=defres(T)) =
            $_op(T, bounds_to_tile_indices(T, bounds); res)
        $_op(T::Type{CopernicusDEM}, bounds::Extents.Extent; res=defres(T)) =
            $_op(T, bounds_to_tile_indices(T, bounds); res)

        # Public function definition with keyword arguments. `extent` is the
        # canonical spatial keyword; `bounds` is the legacy alias.
        function $op(T::Type{CopernicusDEM};
            res=defres(T), bounds=nothing, extent=nothing, tile_index=nothing,
        )
            _check_res(T, res)
            n_set = !isnothing(bounds) + !isnothing(extent) + !isnothing(tile_index)
            if n_set == 0
                $(QuoteNode(op)) === :getraster ||
                    return joinpath(rasterpath(), "CopernicusDEM", res)
                throw(ArgumentError("One of `extent`, `bounds` or `tile_index` kwarg must be specified"))
            elseif n_set > 1
                throw(ArgumentError("Pass only one of `extent`, `bounds` or `tile_index`"))
            end
            return $_op(T, something(extent, bounds, tile_index); res)
        end
    end
end
